# ======================
# 基础配置
# ======================

# 数据库配置
DB_USERNAME=postgres
DB_PASSWORD=difyai123456
DB_DATABASE=dify

# Redis配置
REDIS_PASSWORD=difyai123456

# 向量数据库配置
VECTOR_STORE=weaviate
WEAVIATE_API_KEY=WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih

# Sandbox配置
SANDBOX_API_KEY=dify-sandbox
SANDBOX_GIN_MODE=release
SANDBOX_WORKER_TIMEOUT=15
SANDBOX_ENABLE_NETWORK=true
SANDBOX_PORT=8194

# SSRF代理配置
SSRF_HTTP_PORT=3128
SSRF_REVERSE_PROXY_PORT=8194

# 文件上传限制
UPLOAD_FILE_SIZE_LIMIT=15
UPLOAD_FILE_BATCH_LIMIT=5

# 服务器配置
SERVER_WORKER_AMOUNT=1
SERVER_WORKER_CLASS=gevent
GUNICORN_TIMEOUT=360
CELERY_WORKER_AMOUNT=1

# 端口映射
EXPOSE_NGINX_PORT=80
EXPOSE_NGINX_SSL_PORT=443