# ==================================================================
# 适配 Docker Compose 1.24 版本的完整 Dify 环境
# 包含: api, worker, web, db, redis, nginx, sandbox, ssrf_proxy, weaviate
# ==================================================================

version: '2.4'

services:
  # API service
  api:
    image: langgenius/dify-api:0.15.5
    restart: always
    environment:
      # 基础配置
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      CONSOLE_WEB_URL: ${CONSOLE_WEB_URL:-}
      SERVICE_API_URL: ${SERVICE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      APP_WEB_URL: ${APP_WEB_URL:-}
      FILES_URL: ${FILES_URL:-}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FILE: /app/logs/server.log
      LOG_FILE_MAX_SIZE: ${LOG_FILE_MAX_SIZE:-20}
      LOG_FILE_BACKUP_COUNT: ${LOG_FILE_BACKUP_COUNT:-5}
      DEBUG: ${DEBUG:-false}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
      SECRET_KEY: ${SECRET_KEY:-sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U}
      INIT_PASSWORD: ${INIT_PASSWORD:-}
      DEPLOY_ENV: ${DEPLOY_ENV:-PRODUCTION}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      MODE: api
      
      # 服务器配置
      DIFY_BIND_ADDRESS: 0.0.0.0
      DIFY_PORT: 5001
      SERVER_WORKER_AMOUNT: ${SERVER_WORKER_AMOUNT:-1}
      SERVER_WORKER_CLASS: ${SERVER_WORKER_CLASS:-gevent}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-360}
      
      # 数据库配置
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-difyai123456}
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-dify}
      SQLALCHEMY_POOL_SIZE: ${SQLALCHEMY_POOL_SIZE:-30}
      SQLALCHEMY_POOL_RECYCLE: ${SQLALCHEMY_POOL_RECYCLE:-3600}
      
      # Redis配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-difyai123456}
      REDIS_DB: 0
      
      # Celery配置
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD:-difyai123456}@redis:6379/1
      CELERY_WORKER_AMOUNT: ${CELERY_WORKER_AMOUNT:-}
      CELERY_WORKER_CLASS: ${CELERY_WORKER_CLASS:-}
      
      # 向量数据库配置
      VECTOR_STORE: ${VECTOR_STORE:-weaviate}
      WEAVIATE_ENDPOINT: http://weaviate:8080
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
      
      # 文件存储配置
      STORAGE_TYPE: ${STORAGE_TYPE:-opendal}
      OPENDAL_SCHEME: ${OPENDAL_SCHEME:-fs}
      OPENDAL_FS_ROOT: storage
      
      # Sandbox配置
      CODE_EXECUTION_ENDPOINT: http://sandbox:8194
      CODE_EXECUTION_API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
      
      # 文件上传限制
      UPLOAD_FILE_SIZE_LIMIT: ${UPLOAD_FILE_SIZE_LIMIT:-15}
      UPLOAD_FILE_BATCH_LIMIT: ${UPLOAD_FILE_BATCH_LIMIT:-5}
      
      # 工作流配置
      WORKFLOW_MAX_EXECUTION_STEPS: ${WORKFLOW_MAX_EXECUTION_STEPS:-500}
      WORKFLOW_MAX_EXECUTION_TIME: ${WORKFLOW_MAX_EXECUTION_TIME:-1200}
      
      # SSRF代理配置
      SSRF_PROXY_HTTP_URL: http://ssrf_proxy:3128
      SSRF_PROXY_HTTPS_URL: http://ssrf_proxy:3128
      
      # CORS配置
      WEB_API_CORS_ALLOW_ORIGINS: ${WEB_API_CORS_ALLOW_ORIGINS:-*}
      CONSOLE_CORS_ALLOW_ORIGINS: ${CONSOLE_CORS_ALLOW_ORIGINS:-*}
    depends_on:
      - db
      - redis
      - weaviate
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - dify-network

  # worker service
  worker:
    image: langgenius/dify-api:0.15.5
    restart: always
    environment:
      # 基础配置
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      CONSOLE_WEB_URL: ${CONSOLE_WEB_URL:-}
      SERVICE_API_URL: ${SERVICE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      APP_WEB_URL: ${APP_WEB_URL:-}
      FILES_URL: ${FILES_URL:-}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FILE: /app/logs/server.log
      LOG_FILE_MAX_SIZE: ${LOG_FILE_MAX_SIZE:-20}
      LOG_FILE_BACKUP_COUNT: ${LOG_FILE_BACKUP_COUNT:-5}
      DEBUG: ${DEBUG:-false}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
      SECRET_KEY: ${SECRET_KEY:-sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U}
      INIT_PASSWORD: ${INIT_PASSWORD:-}
      DEPLOY_ENV: ${DEPLOY_ENV:-PRODUCTION}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      MODE: worker
      
      # 服务器配置
      DIFY_BIND_ADDRESS: 0.0.0.0
      DIFY_PORT: 5001
      SERVER_WORKER_AMOUNT: ${SERVER_WORKER_AMOUNT:-1}
      SERVER_WORKER_CLASS: ${SERVER_WORKER_CLASS:-gevent}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-360}
      
      # 数据库配置
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-difyai123456}
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-dify}
      SQLALCHEMY_POOL_SIZE: ${SQLALCHEMY_POOL_SIZE:-30}
      SQLALCHEMY_POOL_RECYCLE: ${SQLALCHEMY_POOL_RECYCLE:-3600}
      
      # Redis配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-difyai123456}
      REDIS_DB: 0
      
      # Celery配置
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD:-difyai123456}@redis:6379/1
      CELERY_WORKER_AMOUNT: ${CELERY_WORKER_AMOUNT:-}
      CELERY_WORKER_CLASS: ${CELERY_WORKER_CLASS:-}
      
      # 向量数据库配置
      VECTOR_STORE: ${VECTOR_STORE:-weaviate}
      WEAVIATE_ENDPOINT: http://weaviate:8080
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
      
      # 文件存储配置
      STORAGE_TYPE: ${STORAGE_TYPE:-opendal}
      OPENDAL_SCHEME: ${OPENDAL_SCHEME:-fs}
      OPENDAL_FS_ROOT: storage
      
      # Sandbox配置
      CODE_EXECUTION_ENDPOINT: http://sandbox:8194
      CODE_EXECUTION_API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
      
      # 文件上传限制
      UPLOAD_FILE_SIZE_LIMIT: ${UPLOAD_FILE_SIZE_LIMIT:-15}
      UPLOAD_FILE_BATCH_LIMIT: ${UPLOAD_FILE_BATCH_LIMIT:-5}
      
      # 工作流配置
      WORKFLOW_MAX_EXECUTION_STEPS: ${WORKFLOW_MAX_EXECUTION_STEPS:-500}
      WORKFLOW_MAX_EXECUTION_TIME: ${WORKFLOW_MAX_EXECUTION_TIME:-1200}
      
      # SSRF代理配置
      SSRF_PROXY_HTTP_URL: http://ssrf_proxy:3128
      SSRF_PROXY_HTTPS_URL: http://ssrf_proxy:3128
      
      # CORS配置
      WEB_API_CORS_ALLOW_ORIGINS: ${WEB_API_CORS_ALLOW_ORIGINS:-*}
      CONSOLE_CORS_ALLOW_ORIGINS: ${CONSOLE_CORS_ALLOW_ORIGINS:-*}
    depends_on:
      - db
      - redis
      - weaviate
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - dify-network

  # Frontend web application
  web:
    image: langgenius/dify-web:0.15.5
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      SENTRY_DSN: ${WEB_SENTRY_DSN:-}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-0}
      TEXT_GENERATION_TIMEOUT_MS: ${TEXT_GENERATION_TIMEOUT_MS:-60000}
    networks:
      - dify-network

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-difyai123456}
      POSTGRES_DB: ${DB_DATABASE:-dify}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS:-100}
    command: >
      postgres -c 'max_connections=${POSTGRES_MAX_CONNECTIONS:-100}'
               -c 'shared_buffers=${POSTGRES_SHARED_BUFFERS:-128MB}'
               -c 'work_mem=${POSTGRES_WORK_MEM:-4MB}'
               -c 'maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-64MB}'
               -c 'effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-4096MB}'
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    networks:
      - dify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:6-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-difyai123456}
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - dify-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The DifySandbox
  sandbox:
    image: langgenius/dify-sandbox:0.2.11
    restart: always
    environment:
      API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
      GIN_MODE: ${SANDBOX_GIN_MODE:-release}
      WORKER_TIMEOUT: ${SANDBOX_WORKER_TIMEOUT:-15}
      ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
      HTTP_PROXY: ${SANDBOX_HTTP_PROXY:-http://ssrf_proxy:3128}
      HTTPS_PROXY: ${SANDBOX_HTTPS_PROXY:-http://ssrf_proxy:3128}
      SANDBOX_PORT: ${SANDBOX_PORT:-8194}
    volumes:
      - ./volumes/sandbox/dependencies:/dependencies
    networks:
      - dify-network
    depends_on:
      - ssrf_proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8194/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ssrf_proxy server
  ssrf_proxy:
    image: ubuntu/squid:latest
    restart: always
    volumes:
      - ./ssrf_proxy/squid.conf:/etc/squid/squid.conf
    environment:
      HTTP_PORT: ${SSRF_HTTP_PORT:-3128}
      COREDUMP_DIR: ${SSRF_COREDUMP_DIR:-/var/spool/squid}
      REVERSE_PROXY_PORT: ${SSRF_REVERSE_PROXY_PORT:-8194}
      SANDBOX_HOST: sandbox
      SANDBOX_PORT: ${SANDBOX_PORT:-8194}
    networks:
      - dify-network

  # The Weaviate vector store
  weaviate:
    image: semitechnologies/weaviate:1.19.0
    restart: always
    volumes:
      - ./volumes/weaviate:/var/lib/weaviate
    environment:
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      QUERY_DEFAULTS_LIMIT: ${WEAVIATE_QUERY_DEFAULTS_LIMIT:-25}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:-false}
      DEFAULT_VECTORIZER_MODULE: ${WEAVIATE_DEFAULT_VECTORIZER_MODULE:-none}
      CLUSTER_HOSTNAME: ${WEAVIATE_CLUSTER_HOSTNAME:-node1}
      AUTHENTICATION_APIKEY_ENABLED: ${WEAVIATE_AUTHENTICATION_APIKEY_ENABLED:-true}
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
      AUTHENTICATION_APIKEY_USERS: ${WEAVIATE_AUTHENTICATION_APIKEY_USERS:-hello@dify.ai}
      AUTHORIZATION_ADMINLIST_ENABLED: ${WEAVIATE_AUTHORIZATION_ADMINLIST_ENABLED:-true}
      AUTHORIZATION_ADMINLIST_USERS: ${WEAVIATE_AUTHORIZATION_ADMINLIST_USERS:-hello@dify.ai}
    networks:
      - dify-network
    ports:
      - "8080:8080"

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/app/storage:/usr/share/nginx/html/storage
    depends_on:
      - api
      - web
    ports:
      - "${EXPOSE_NGINX_PORT:-80}:80"
      - "${EXPOSE_NGINX_SSL_PORT:-443}:443"
    networks:
      - dify-network

networks:
  dify-network:
    driver: bridge